# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- checkout: self
  clean: false 

- powershell: |
    &"$(System.DefaultWorkingDirectory)/tests/runPSScriptAnalyzer.ps1"
  displayName: 'Run PSScriptAnalyzer'

- powershell: |
    &"$(System.DefaultWorkingDirectory)/tests/_InvokeTests.ps1"
  displayName: 'Run Pester Tests'

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: "$(System.DefaultWorkingDirectory)/updateVersionNumber.ps1"
    displayName: 'Update Module Version Number'
    arguments: "-VersionNumber $(Build.BuildId)"

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: |
      **/*test*.xml
      searchFolder: '$(Build.ArtifactStagingDirectory)/tests'
      failTaskOnFailedTests: true
  condition: succeededOrFailed()

- task: CopyFiles@2
  inputs:
    contents: '**' 
    targetFolder: "$(Build.ArtifactStagingDirectory)"

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)\noddyModule'
  inputs:
    SourceFolder: noddyModule
    TargetFolder: '$(build.artifactstagingdirectory)\noddyModule'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)\artifact'
  inputs:
    SourceFolder: artifact
    TargetFolder: '$(build.artifactstagingdirectory)\artifact'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)\artifact'
    ArtifactName: artifact

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: noddyModule'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)\noddyModule'
    ArtifactName: noddyModule