# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- checkout: self
  clean: false 

- powershell: |
    &"$(System.DefaultWorkingDirectory)/tests/runPSScriptAnalyzer.ps1"
  displayName: 'Run PSScriptAnalyzer'

- powershell: |
    &"$(System.DefaultWorkingDirectory)/tests/_InvokeTests.ps1"
  displayName: 'Run Pester Tests'

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: "$(System.DefaultWorkingDirectory)/noddyModule/updateVersionNumber.ps1"
    displayName: 'Update Module Version Number'
    arguments: "-VersionNumber $(Build.BuildId)"

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: NUnit
    testResultsFiles: |
      **/*test*.xml
      searchFolder: '$(Build.ArtifactStagingDirectory)/tests'
      failTaskOnFailedTests: true
  condition: succeededOrFailed()

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'noddyModule'
    targetPath: '$(Build.ArtifactStagingDirectory)/noddyModule'