#
# Module manifest for module azure.databricks.cicd.tools'
#
# Generated by: Simon D'Morias @ Datathirst.net
#
# Generated on: 09/07/2018
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'noddyModule.psm1'

    # Version number of this module.
    ModuleVersion = '0.0.0'

    # ID used to uniquely identify this module
    GUID = '3ca1b668-e2c2-49c8-aabb-d9dd4306fb60'

    # Author of this module
    Author = "Richie Lee"

    # Company or vendor of this module
    CompanyName = 'RichieBzzzt'

    # Copyright statement for this module
    Copyright = 'RichieBzzzt'

    # Description of the functionality provided by this module
    Description = 'A smaple PowerShell module to demonstrate how to publish a PowerShell Module to Azure DevOps Artifacts'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @('')

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = 'path.ps1xml'

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module
    FunctionsToExport = 'Show-Message'

    # Cmdlets to export from this module
    CmdletsToExport = ''

    # Variables to export from this module
    VariablesToExport = ''

    # Aliases to export from this module
    AliasesToExport = ''

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # HelpInfo URI of this module
    HelpInfoURI = 'https://github.com/RichieBzzzt/azdo-psmodule-artifact'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

    }
